travis:
  secure:
    BINSTAR_TOKEN: Oswzc2EEf8MLBk90erPmj/VgJSPMgDhOjEsHB9VVdY3ZF5fyBzj5S1awmGFMr0Xv8GtnjGvJAExr09jR2KxbjwPPEsZnh1caGJHC8jH03J6XU4WIVHjF2kja+sQJr1mMA2yhbMfXGgMFtTMPrQgHwg+7xOqsiYYjos1sRXZaVXRYNleJqChJBlYkXwgwaUVO0i7JYQBBddKWapkyaHv3O6vpJPRy4AFqgjaAH2CADnVeZ/qZO0m5khCsFcTZQjZ9IOtfUu5hNmRHQiU/Q3UycjeirmfPexyYCPrPgOhn1uHhsLwf/3/ZOasv47nvWb6aPLoqVsJhJV4UXH2wVkla9itmVL3CKT6VwaJARX6BqiSrVL1tacS8xHBYslBUfrnyPVEDULU5ZpzC+nbkkeyNf+crRHmZw7D8k/aSrUNTNP0e1tu/CskFhLDgGrRElKWGPw0Eguvfp2tjwR7EEmTIytx71dasCz0rfpFvTFi3wmRov/X88ipewJM45zqNvL2hcYF8DmQO88FSepYXByipbawcbsr+8TIJ57Zh4XkHUbCrauvlbREZBefcqxaDMb//8BSjnwtAOY0Hr8mAKHr9torQ/T6mV3VasFdjthuEK9bAWYS3hUQYYs5qYv4iLFz2CFhf1D8DtwTQZ6lZnBr6JPdtSxdWVIEcnPmFI2VpnWI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
